### ISSUE TITLE
False positive for named argument checks when using a == operator in an argument

### ISSUE THREAD

**Issue by stof** [friendsoftwig/twigcs#162]
```twig
{{- mdc_tab(
        'onboarding_program.menu.in_progress'|trans,
        path('training_program_list'),
        completed == false,
        'extra arg'
    ) -}}
```

This reports an error on the `=` sign in `completed == false` saying `ERROR There should be 0 space before the "=" in the named arguments list.` but this is not a named argument list

**Comment by Ciloe** [comment]
Normaly, it's fixed by #156

**Comment by stof** [comment]
any ETA for a release containing the fix ?

**Comment by Ciloe** [comment]
We are passing an other fix, I think @OwlyCode will can create a release after this.

**Comment by stof** [comment]
checking things again, my project is already using the master branch at d5f5a03fcc524fe48679c1ac29d553d4b329c3f7

This means that the PR #156 does not actually fix this issue.

**Comment by Ciloe** [comment]
Ok, I will check this

**Comment by Ciloe** [comment]
@stof  I had this use case in the tests file, and I have no error's displayed. For example : 
`Twig3FunctionalTest.php` at line 153
```php
            ["{{ function(foo, bar == false) }}", null],
```
And launched `bin/phpunit ./tests/Twig3FunctionalTest.php`

**Comment by stof** [comment]
@Ciloe I fixed the code snippet. I reduced it too much when opening the issue. Triggering the error requires that the expression using `==` is not last argument of the call. this case fails in the tests:

```php
 ['{{ function(foo, bar == false, baz) }}', null],
```

**Comment by Ciloe** [comment]
Ha, nice. I'm working on it. Thanks for your feedback

**Comment by stof** [comment]
waiting on https://github.com/friendsoftwig/twigcs/pull/164
